title: 'We are #MiamiTech'
description: 'Miamians building an equitable, collaborative, inclusive and thriving community for makers, technologists, and advocates in the 305.'
theme: jekyll-theme-cayman
google_analytics:
url: 'http://wearemiamitech.com'
twitter:
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/socialimg.png
