title: 'We are #MiamiTech'
description: Join us in building an equitable, collaborative, diverse and thriving community for makers, technologists, and advocates in the 305.
theme: jekyll-theme-cayman
google_analytics:
url: 'http://wearemiamitech.com'
twitter:
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/socialimg.png
